### ISSUE TITLE
After registration, new error

### ISSUE THREAD

**Issue by PhieF** [nextcloud/terms_of_service#160]
Hi, still have an issue when registering a new user

After registering I get this error

```
Renseignements techniques

    Adresse distante : 192.168.1.13
    ID de la demande : XaW8OvdGtpDtjmrV5NVb
    Type : OCP\Files\ForbiddenException
    Code : 0
    Message : Terms of service not signed!
    Fichier : /var/www/html/nextcloudservice/apps/terms_of_service/lib/Filesystem/StorageWrapper.php
    Ligne : 88


Trace

#0 /var/www/html/nextcloudservice/lib/private/Files/View.php(1150): OCA\TermsOfService\Filesystem\StorageWrapper->fopen('files/Nextcloud...', 'w')
#1 /var/www/html/nextcloudservice/lib/private/Files/View.php(986): OC\Files\View->basicOperation('fopen', '/phoenamandre/f...', Array, 'w')
#2 /var/www/html/nextcloudservice/lib/private/Files/Node/File.php(108): OC\Files\View->fopen('/phoenamandre/f...', 'w')
#3 /var/www/html/nextcloudservice/lib/private/legacy/util.php(472): OC\Files\Node\File->fopen('w')
#4 /var/www/html/nextcloudservice/lib/private/legacy/util.php(435): OC_Util::copyr('/var/www/html/n...', Object(OC\Files\Node\Folder))
#5 /var/www/html/nextcloudservice/lib/private/User/Session.php(515): OC_Util::copySkeleton('phoenamandre', Object(OC\Files\Node\Folder))
#6 /var/www/html/nextcloudservice/lib/private/User/Session.php(373): OC\User\Session->prepareUserLogin(true, false)
#7 /var/www/html/nextcloudservice/lib/private/User/Session.php(576): OC\User\Session->completeLogin(Object(OC\User\User), Array, false)

```

thanks for your work ! :)

**Comment by nickvergessen** [comment]
Do you mean login or registration?

**Comment by PhieF** [comment]
Registration process leading to login

you can try it here

https://cloud.exode.me

just try to create an account, after email verification you will get this error
perhaps it is an issue with the registration app ?

**Comment by nickvergessen** [comment]
Registration integration is working by now
